import React, { useEffect, useState } from "react";
import apiClient from "../utils/api";
import { currency } from "../utils/format";
import { STORAGE_KEYS, HOSPITAL_NAME, HOSPITAL_ADDR, HOSPITAL_PHONE } from "../constants";

export default function InvoicePage() {
  const [invoice, setInvoice] = useState(null);

  const params  = new URLSearchParams(window.location.search);
  const bill_id = params.get("bill");

  useEffect(() => {
    const load = async () => {
      try {
        const res = await apiClient.get(`/billing/invoice/${bill_id}`);
        setInvoice(res.data);
        setTimeout(() => window.print(), 800);
      } catch (err) {
        console.error(err);
      }
    };
    load();
  }, [bill_id]);

  if (!invoice) return <h2 style={{ padding: 20, fontFamily: "var(--font)" }}>Loading invoice...</h2>;

  const { bill, items, patient } = invoice;
  const user = localStorage.getItem(STORAGE_KEYS.EMAIL) || "Counter Staff";

  return (
    <div style={{ maxWidth:"900px", margin:"30px auto", fontFamily:"var(--font)", background:"#ffffff", borderRadius:"16px", boxShadow:"0 4px 15px rgba(0,0,0,0.12)", paddingBottom:"30px" }}>
      <div style={{ background:"linear-gradient(135deg, #154360, #2E86C1)", color:"white", padding:"35px", borderTopLeftRadius:"16px", borderTopRightRadius:"16px", display:"flex", justifyContent:"space-between", alignItems:"center" }}>
        <div>
          <h1 style={{ margin:0, fontSize:"28px", fontWeight:"700" }}>{HOSPITAL_NAME}</h1>
          <p style={{ margin:"5px 0", opacity:0.9 }}>{HOSPITAL_ADDR}<br/>{HOSPITAL_PHONE}</p>
        </div>
        <div style={{ textAlign:"right" }}>
          <div style={{ background:"rgba(255,255,255,0.2)", padding:"10px 20px", borderRadius:"10px", marginBottom:"10px" }}>
            <div style={{ fontSize:"12px", opacity:0.8 }}>INVOICE NUMBER</div>
            <div style={{ fontSize:"20px", fontWeight:"700" }}>{bill.invoice_number}</div>
          </div>
          <div style={{ background:"rgba(255,255,255,0.2)", padding:"10px 20px", borderRadius:"10px" }}>
            <div style={{ fontSize:"12px", opacity:0.8 }}>DATE</div>
            <div style={{ fontSize:"20px", fontWeight:"700" }}>{bill.date}</div>
          </div>
        </div>
      </div>

      <div style={{ padding:"30px" }}>
        <h3 style={{ marginBottom:5 }}>Bill To</h3>
        <h2 style={{ margin:0 }}>{patient.name}</h2>
        <p style={{ marginTop:5, opacity:0.8 }}>{patient.gender}, {patient.age}</p>
        <h3 style={{ marginTop:25 }}>Patient ID</h3>
        <h2 style={{ marginTop:0, fontWeight:"700" }}>{bill.bill_id.toString().padStart(6,"0")}</h2>
      </div>

      <table style={{ width:"100%", borderCollapse:"collapse", marginTop:"10px" }}>
        <thead>
          <tr style={{ background:"#f5f8ff", textAlign:"left" }}>
            <th style={{ padding:"12px 20px" }}>DESCRIPTION</th>
            <th style={{ padding:"12px 20px" }}>QTY</th>
            <th style={{ padding:"12px 20px" }}>PRICE</th>
            <th style={{ padding:"12px 20px" }}>AMOUNT</th>
          </tr>
        </thead>
        <tbody>
          {items.map((it, idx) => (
            <tr key={idx}>
              <td style={{ padding:"12px 20px", borderBottom:"1px solid #eee" }}>{it.name}</td>
              <td style={{ padding:"12px 20px", borderBottom:"1px solid #eee" }}>{it.qty}</td>
              <td style={{ padding:"12px 20px", borderBottom:"1px solid #eee" }}>{currency(it.price)}</td>
              <td style={{ padding:"12px 20px", borderBottom:"1px solid #eee" }}>{currency(it.subtotal)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div style={{ marginTop:"25px", textAlign:"right", paddingRight:"30px" }}>
        <div style={{ display:"inline-block", padding:"18px 25px", border:"2px solid #2E86C1", borderRadius:"12px" }}>
          <div style={{ marginBottom:6, fontSize:"16px" }}><b>Subtotal:</b> {currency(bill.total)}</div>
          <div style={{ fontSize:"20px", fontWeight:"700" }}>Total: {currency(bill.net_total)}</div>
        </div>
      </div>

      <p style={{ paddingLeft:30, marginTop:40, opacity:0.6 }}>Generated by <b>{user}</b></p>
    </div>
  );
}
